---
- hosts: all
  tasks:
    - name: copy provisionning files
      copy:
        src: "{{item}}"
        dest: /home/stagiaire/ansible/
        owner: stagiaire
        group: stagiaire
      loop:
        - 'Vagrantfile'
        - 'id_rsa'
        - 'id_rsa.pub'
        - 'setup.sh'

    - name: setup VirtualBox
      block:
      - name: install dnf package manager
        yum:
          name: dnf

      - name: remove Virtualbox 5
        dnf:
          name: VirtualBox-5.1
          state: absent

      - name: Install Virtualbox 6
        dnf:
          name: VirtualBox-6.1
          state: present
        notify:
          - reboot VMs
      become: yes

    - name: setup vagrant
      block:
      - name: set hashicorp Repo
        get_url:
          url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          dest: /etc/yum.repos.d/
          validate_certs: false

      - name: install vagrant
        yum:
          name: "{{item}}"
        loop:
          - yum-utils
          - vagrant
      become: yes
      
    - name: create infrastructure
      shell:
        chdir: /home/stagiaire/ansible
        cmd: vagrant up

  handlers:
  - name: reboot VMs
    become: yes
    shell:
      cmd: reboot
